---
- name: Configure local machines
  hosts: localhosts
  roles:
    - dependencies
    - bootstrap

- name: Configure bastion machines
  hosts: bastions
  roles:
    - dependencies
    - docker
    - pdns
    - networking
    - kea
    - lxc
    - kubernetes
    - etcd

- name: Configure nodes
  hosts: nodes
  roles:
    - nodes

- name: Configure master nodes
  hosts: master_nodes
  tasks:
    - include_role:
        name: nodes
        tasks_from: masters

- name: Configure worker nodes
  hosts: worker_nodes
  roles:
    - include_role:
        name: nodes
        tasks_from: workers
