FROM phusion/baseimage:latest

RUN apt update \
    && apt install -y --no-install-recommends \
            libssl-dev \
            libtool \
            pdns-recursor \
    && apt-get clean \
    && rm -rf \
        /var/lib/apt/lists/* \
        /tmp/* \
        /var/tmp/*

RUN mkdir /etc/service/pdns_recursor
COPY ./powerdns/recursor/recursor.sh /etc/service/pdns_recursor/run
RUN chmod 0755 /etc/service/pdns_recursor/run

COPY ./powerdns/recursor/recursor.conf /etc/powerdns/recursor.conf
RUN chmod 0600 /etc/powerdns/recursor.conf \
    && chown root:root /etc/powerdns/recursor.conf

CMD ["/sbin/my_init"]
