version: '2'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      PGDATABASE: pdns
      PGPASSWORD: "{{ pdns_db_password }}"
      PGUSER: postgres
    hostname: pdns_db
    network_mode: host
    ports:
      - "5432:5432/tcp"
    restart: always
    volumes:
      - /var/lib/pdns/db:/var/lib/postgresql/data

  recursor:
    build:
      context: .
      dockerfile: Dockerfile.recursor
    depends_on:
      - db
    hostname: recursor
    network_mode: host
    ports:
      - "{{ dns_recursor }}:5353:5353/tcp"
      - "{{ dns_recursor }}:5353:5353/udp"
    restart: always

  nameserver:
    build:
      context: .
      dockerfile: Dockerfile.nameserver
    depends_on:
      - recursor
    hostname: nameserver
    network_mode: host
    ports:
      - "{{ dns_nameserver }}:53:53/tcp"
      - "{{ dns_nameserver }}:53:53/udp"
    restart: always
