---
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/03-auth-configs.md

- name: Generate bootstrap token
  shell: head -c 16 /dev/urandom | od -An -t x | tr -d ' '
  register: bootstrap_token_output

- name: Define bootstrap_token
  set_fact:
    bootstrap_token: "{{ bootstrap_token_output.stdout }}"

- name: Create token.csv
  copy:
    content: '{{ bootstrap_token }},kubelet-bootstrap,10001,"system:kubelet-bootstrap"'
    dest: "{{ home }}/cfssl//token.csv"

- name: Distribute TLS bootstrap token file to each master node
  copy:
    src: "{{ home }}/cfssl//token.csv"
    dest: "{{ item.home }}/token.csv"
    remote_src: True
  with_items: "{{ master_nodes.values() }}"
  become: true

- name: Create bootstrap.kubeconfig
  shell: |
    kubectl config set-cluster cluster01 \
      --certificate-authority=ca.pem \
      --embed-certs=true \
      --server=https://{{ phys_intf_ip }}:6443 \
      --kubeconfig=bootstrap.kubeconfig

    kubectl config set-credentials kubelet-bootstrap \
      --token={{ bootstrap_token }} \
      --kubeconfig=bootstrap.kubeconfig

    kubectl config set-context default \
      --cluster=cluster01 \
      --user=kubelet-bootstrap \
      --kubeconfig=bootstrap.kubeconfig

    kubectl config use-context default \
      --kubeconfig=bootstrap.kubeconfig
  args:
    chdir: "{{ home }}/cfssl"
    creates: "{{ home }}/cfssl/bootstrap.kubeconfig"

- name: Create kube-proxy.kubeconfig
  shell: |
    kubectl config set-cluster cluster01 \
      --certificate-authority=ca.pem \
      --embed-certs=true \
      --server=https://{{ phys_intf_ip }}:6443 \
      --kubeconfig=kube-proxy.kubeconfig

    kubectl config set-credentials kube-proxy \
      --client-certificate=kube-proxy.pem \
      --client-key=kube-proxy-key.pem \
      --embed-certs=true \
      --kubeconfig=kube-proxy.kubeconfig

    kubectl config set-context default \
      --cluster=cluster01 \
      --user=kube-proxy \
      --kubeconfig=kube-proxy.kubeconfig

    kubectl config use-context default \
      --kubeconfig=kube-proxy.kubeconfig
  args:
    chdir: "{{ home }}/cfssl"
    creates: "{{ home }}/cfssl/kube-proxy.kubeconfig"

- name: Distribute bootstrap.kubeconfig to worker nodes
  copy:
    src: "{{ home }}/cfssl/bootstrap.kubeconfig"
    dest: "{{ item.home }}/bootstrap.kubeconfig"
    remote_src: True
  with_items: "{{ worker_nodes.values() }}"
  become: true

- name: Distribute kube-proxy.kubeconfig to worker nodes
  copy:
    src: "{{ home }}/cfssl/kube-proxy.kubeconfig"
    dest: "{{ item.home }}/kube-proxy.kubeconfig"
    remote_src: True
  with_items: "{{ worker_nodes.values() }}"
  become: true

- name: Assign ownership of copied files to LXC user
  shell: |
    uid_gid=$(ls -la {{ item.home }}/.bashrc | awk '{printf "%d:%d", $3, $4}')
    chown -R ${uid_gid} {{ item.home }}
  with_items: "{{ nodes.values() }}"
  become: true
