---
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/02-certificate-authority.md

- name: Download cfssl binary
  get_url:
    url: "https://pkg.cfssl.org/R1.2/cfssl_linux-amd64"
    dest: "/usr/local/bin/cfssl"
    mode: 0755
  become: true

- name: Download cfssljson binary
  get_url:
    url: "https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64"
    dest: "/usr/local/bin/cfssljson"
    mode: 0755
  become: true

- name: Create cfssl directory
  file:
    mode: 0755
    path: "{{ home }}/cfssl"
    state: directory

- name: Copy templated cfssl files
  template:
    src: "{{ item.src }}"
    dest: "{{ home }}/cfssl/{{ item.path }}"
  with_filetree: "{{ role_path }}/files/cfssl"
  when: item.state == 'file'


- name: Generate ca.pem and ca-key.pem
  shell: cfssl gencert -initca ca-csr.json | cfssljson -bare ca;
  args:
    chdir: "{{ home }}/cfssl"

- name: Verify existence of ca.pem and ca-key.pem
  include_role:
    name: common
    tasks_from: assert_file_exists
  with_items:
    - "{{ home }}/cfssl/ca.pem"
    - "{{ home }}/cfssl/ca-key.pem"
  loop_control:
    loop_var: check_file_path


- name: Generate admin.pem, admin.csr and admin-key.pem
  shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
      admin-csr.json | cfssljson -bare admin
  args:
    chdir: "{{ home }}/cfssl"

- name: Verify existence of admin.pem, admin.csr, and admin-key.pem
  include_role:
    name: common
    tasks_from: assert_file_exists
  with_items:
    - "{{ home }}/cfssl/admin.pem"
    - "{{ home }}/cfssl/admin.csr"
    - "{{ home }}/cfssl/admin-key.pem"
  loop_control:
    loop_var: check_file_path


- name: Generate kube-proxy.csr, kube-proxy.pem, and kube-proxy-key.pem
  shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
      kube-proxy-csr.json | cfssljson -bare kube-proxy
  args:
    chdir: "{{ home }}/cfssl"

- name: Verify existence of kube-proxy.csr, kube-proxy.pem, and kube-proxy-key.pem
  include_role:
    name: common
    tasks_from: assert_file_exists
  with_items:
    - "{{ home }}/cfssl/kube-proxy.csr"
    - "{{ home }}/cfssl/kube-proxy.pem"
    - "{{ home }}/cfssl/kube-proxy-key.pem"
  loop_control:
    loop_var: check_file_path


- name: Generate kubernetes.pem, kubernetes.csr, and kubernetes-key.pem
  shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
      kubernetes-csr.json | cfssljson -bare kubernetes
  args:
    chdir: "{{ home }}/cfssl"

- name: Verify existence of kubernetes.pem, kubernetes.csr, and kubernetes-key.pem
  include_role:
    name: common
    tasks_from: assert_file_exists
  with_items:
    - "{{ home }}/cfssl/kubernetes.pem"
    - "{{ home }}/cfssl/kubernetes.csr"
    - "{{ home }}/cfssl/kubernetes-key.pem"
  loop_control:
    loop_var: check_file_path


- name: Copy TLS certificates and keys to worker nodes
  shell: |
    for auth_file in ca.pem kube-proxy.pem kube-proxy-key.pem; do
      cp ${auth_file} {{ item.value.home }}/${auth_file};
    done;
  args:
    chdir: "{{ home }}/cfssl"
  with_dict: "{{ worker_nodes }}"
  become: true

- name: Copy TLS certificates and keys to controller nodes
  shell: |
    for auth_file in ca.pem ca-key.pem kubernetes-key.pem kubernetes.pem; do
      cp ${auth_file} {{ item.value.home }}/${auth_file};
    done;
  args:
    chdir: "{{ home }}/cfssl"
  with_dict: "{{ controller_nodes }}"
  become: true

- name: Assign ownership of files copied to nodes to LXC user
  shell: |
    uid_gid=$(ls -la {{ item.value.home }}/.bashrc | awk '{printf "%d:%d", $3, $4}')
    chown -R ${uid_gid} {{ item.value.home }}/
  with_dict: "{{ nodes }}"
  become: true
