---
- name: Detect /usr/bin/kube-apiserver
  stat:
    path: /usr/bin/kube-apiserver
  register: kube_apiserver

- name: Define kube_apiserver_version_resp
  shell: kube-apiserver --version | awk '{print $2}';
  register: kube_apiserver_version_resp
  when: kube_apiserver.stat.exists

- name: Define kube_apiserver_version
  set_fact:
    kube_apiserver_version: "{{ kube_apiserver_version_resp.stdout | default('-1') }}"

- name: Downloading kube-apiserver binary
  get_url:
    url: "{{ k8s_download_url }}/kube-apiserver"
    dest: "/usr/bin/kube-apiserver"
    mode: 0755
    force: yes
  become: true
  when: kube_apiserver_version != k8s_version

- name: Generate systemd unit file
  copy:
    dest: /etc/systemd/system/kube-apiserver.service
    mode: 0777
    content: |
      [Unit]
      Description=Kubernetes API Server
      Documentation=https://github.com/GoogleCloudPlatform/kubernetes

      [Service]
      ExecStart=/usr/bin/kube-apiserver \
        --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota \
        --advertise-address=0.0.0.0 \
        --allow-privileged=true \
        --apiserver-count=3 \
        --audit-log-maxage=30 \
        --audit-log-maxbackup=3 \
        --audit-log-maxsize=100 \
        --audit-log-path=/var/log/kubernetes/kube-apiserver.log \
        --authorization-mode=RBAC \
        --bind-address=0.0.0.0 \
        --client-ca-file=/var/lib/kubernetes/auth/ca.pem \
        --enable-swagger-ui=true \
        --etcd-cafile=/var/lib/kubernetes/auth/ca.pem \
        --etcd-certfile=/var/lib/kubernetes/auth/kubernetes.pem \
        --etcd-keyfile=/var/lib/kubernetes/auth/kubernetes-key.pem \
        --etcd-servers=https://127.0.0.1:2379 \
        --event-ttl=1h \
        --experimental-bootstrap-token-auth \
        --insecure-bind-address=127.0.0.1 \
        --kubelet-certificate-authority=/var/lib/kubernetes/auth/ca.pem \
        --kubelet-client-certificate=/var/lib/kubernetes/auth/kubernetes.pem \
        --kubelet-client-key=/var/lib/kubernetes/auth/kubernetes-key.pem \
        --kubelet-https=true \
        --runtime-config=rbac.authorization.k8s.io/v1alpha1 \
        --service-account-key-file=/var/lib/kubernetes/auth/ca-key.pem \
        --service-cluster-ip-range=10.32.0.0/24 \
        --service-node-port-range=30000-32767 \
        --tls-cert-file=/var/lib/kubernetes/auth/kubernetes.pem \
        --tls-private-key-file=/var/lib/kubernetes/auth/kubernetes-key.pem \
        --token-auth-file=/var/lib/kubernetes/auth/token.csv \
        --v=2
      Restart=on-failure
      RestartSec=5

      [Install]
      WantedBy=multi-user.target
  become: true

- name: Update systemd
  include_role:
    name: common
    tasks_from: reload_systemd_service
  vars:
    service_name: kube-apiserver.service
