---
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs

- include: kubectl.yml
- include: auth-config.yml
- include: certificate-authority.yml

- name: Create /var/log/kubernetes directory
  file:
    path: "/var/log/kubernetes"
    state: directory
  become: true

- name: Create /var/lib/kubernetes directory
  file:
    path: "/var/lib/kubernetes"
    state: directory
  become: true

- name: Copy auth files into /var/lib/kubernetes
  copy:
    src: "{{ home }}/cfssl/{{ item }}"
    dest: "/var/lib/kubernetes/{{ item }}"
    remote_src: True
  with_items:
    - ca.pem
    - ca-key.pem
    - kubernetes-key.pem
    - kubernetes.pem
    - token.csv
  become: true

- include: kube-apiserver.yml
- include: kube-controller-manager.yml
- include: kube-scheduler.yml
