---
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs

- include: kubectl.yml
- include: certificate-authority.yml
- include: auth-config.yml


- name: Create kubernetes directories on nodes
  file:
    path: "{{ item[0].rootfs }}/{{ item[1] }}"
    state: directory
    recurse: yes
    owner: 100000
    group: 100000
  with_nested:
    - "{{ nodes.values() }}"
    - ['/var/lib/kubernetes/auth', '/var/log/kubernetes']
  become: true

- name: Define master_auth_files
  set_fact:
    master_auth_files:
      - ca.pem
      - ca-key.pem
      - kubernetes-key.pem
      - kubernetes.pem
      - token.csv

- name: Copy auth files into /var/lib/kubernetes on master nodes
  copy:
    src: "{{ home }}/cfssl/{{ item[1] }}"
    dest: "{{ item[0].rootfs }}/var/lib/kubernetes/auth/{{ item[1] }}"
    owner: 100000
    group: 100000
    remote_src: True
  with_nested:
    - "{{ master_nodes.values() }}"
    - "{{ master_auth_files }}"
  become: true


- name: Define worker_auth_files
  set_fact:
    worker_auth_files:
      - ca.pem
      - kube-proxy.pem
      - kube-proxy-key.pem

- name: Copy auth files into /var/lib/kubernetes on worker nodes
  copy:
    src: "{{ home }}/cfssl/{{ item[1] }}"
    dest: "{{ item[0].rootfs }}/var/lib/kubernetes/auth/{{ item[1] }}"
    owner: 100000
    group: 100000
    remote_src: True
  with_nested:
    - "{{ worker_nodes.values() }}"
    - "{{ worker_auth_files }}"
  become: true
