version: '2'
services:
  ddns:
    build:
      context: .
      dockerfile: Dockerfile.ddns
    hostname: ddns
    network_mode: host
    ports:
      - "{{ ddns_server }}:53001:53001/udp"
    restart: always
    volumes:
      - /var/lib/kea:/var/lib/kea
      - ./kea/ddns/ddns.json:/etc/kea/ddns.json

  dhcp4:
    build:
      context: .
      dockerfile: Dockerfile.dhcp4
    hostname: dhcp4
    network_mode: "host"
    ports:
      - "{{ dhcp4_server }}:67:67/udp"
      - "{{ dhcp4_server }}:68:68/udp"
    restart: always
    volumes:
      - /var/lib/kea:/var/lib/kea
      - ./kea/dhcp4/dhcp4.json:/etc/kea/dhcp4.json
