FROM phusion/baseimage:latest

RUN apt update \
    && apt install -y --no-install-recommends \
        kea-common \
        kea-dev \
        kea-dhcp-ddns-server \
    && apt-get clean \
    && rm -rf \
        /var/lib/apt/lists/* \
        /tmp/* \
        /var/tmp/*

RUN mkdir /etc/service/kea_ddns
COPY ./kea/ddns/ddns.sh /etc/service/kea_ddns/run
RUN chmod 0755 /etc/service/kea_ddns/run

CMD ["/sbin/my_init"]
