---
- name: Reload service
  systemd:
    name: "{{ service_name }}"
    daemon_reload: yes
  become: true

- name: Enable service
  systemd:
    name: "{{ service_name }}"
    enabled: yes
  become: true

- name: Start service
  systemd:
    name: "{{ service_name }}"
    state: started
  become: true
