---
- name: Install apt dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - bridge-utils
    - build-essential
    - python-netaddr
    - sshpass
  become: true

- name: Install pip dependencies
  pip:
    name: "{{ item }}"
  with_items:
    - dnspython
    - netaddr
    - PyYAML
  become: true
